---
title: "GRANTS AND AWARDS"
---

## Awards

### 2023

-   2023 - **Raine BrightSpark Research Prize,** *Raine Medical Research Foundation*

-   2023 - **Global Health Research Award,** *IPUMS DHS and IPUMS PMA*

### 2022

-   2022 - **Early- and Mid-Career Reaearcher (EMCR) of the Year**, *enAble Institute, Curtin*

-   2022 - **Raine Research Prize,** *Raine Medical Research Foundation*

-   2022 - **STEM Early Career Researcher of the Year,** *Curtin University*

-   2022- **Commendation in Research Supervision**, Excellence in Teaching Awards, *Curtin University*

-   2022 - **Early Career Researcher of the Year** for Faculty of Health Sciences, *Curtin University*

-   2022 - **WA Young Tall Poppy Awards**, *Australian Institute of Policy and Science*

### 2021

-   2021- Finalist for **Business, Society & Community ECR the Year Award**, *Curtin University*

### 2020

-   2020- **Health and Medical Research Council Emerging Leadership Fellowship,** Australia 

-   2020- **Charter Hall Research Collaboration Award**, *Raine Medical Research Foundation*, WA

### 2019 - 2014

-   2019 - **The Gro Harlem Brundtland Visiting Scholarship**, *Norwegian Institute of Public Health*

-   2018- **Dean's Commendation for Doctoral Thesis Excellence,** *University of Adelaide*

-   2017 - **DR Strank Travelling Fellowship**, *the University of Adelaide*

-   2016 - **Research Abroad Scholarship**, *the University of Adelaide*

-   2015 - **Adelaide Scholarship International,** *the University of Adelaide*

-   2014 - **Demograhic and Health Survey (DHS) Fellowship,** *ICF International and DHS Program, US*

## RESEARCH GRANTS
