---
title: "Publications"
---

I published \>115 peer-reviewed journal articles, and the remaining are working paper and a policy brief. I was first, second or last author for over 60 articles. As part of the Ethiopian National Burden of Diseases (ENBD) team where I was vice chair, I led and coordinated 10 publications using GBD methods in Ethiopia.

**Top 10 Publications**

-   Tessema, G. A., S. E. Håberg, G. Pereira, A. K. Regan, J. Dunne, and M. C. Magnus. 2022. "[Interpregnancy interval and adverse pregnancy outcomes among pregnancies following miscarriages or induced abortions in Norway (2008-2016): A cohort study](10.1371/journal.pmed.1004129)." PLoS Medicine 19 (11)

-   Tessema, G. A., J. S. Gomersall, C. O. Laurence, and M. A. Mahmood. 2019. "[Healthcare providers' perspectives on use of the national guideline for family planning services in Amhara Region, Ethiopia: A qualitative study](https://doi.org/10.1136/bmjopen-2018-023403)." BMJ Open 9 (2)

-   Tessema, G., Y. Kinfu, B. A. Dachew, A. Tesema, Y. Assefa, K. Alene, and et al., "T[he COVID-19 pandemic and healthcare systems in Africa: a scoping review of preparedness, impact and response](https://doi.org/10.1136/bmjgh-2021-007179)." BMJ Global Health 6 (12). Inpress.

-   Dunne, J., D. Foo, B. A. Dachew, B. Duko, A. T. Gebremedhin, S. D. Nyadanu, G. Pereira, and G. Tessema. 2024. "[Diabetic and hypertensive disorders following early pregnancy loss: a systematic review and meta-analysis](https://doi.org/10.1016/j.eclinm.2024.102560)." EClinicalMedicine : 102560-102560.

-   Tessema, G. A., S. E. Håberg, G. Pereira, and M. C. Magnus. 2022. "The role of intervening pregnancy loss in the association between interpregnancy interval and adverse pregnancy outcomes." BJOG: An International Journal of Obstetrics and Gynaecology 129 (11): 1853-1861.

-   Tessema, G. A., and G. Pereira. 2020. "[Challenging the assumption that interpregnancy interval causes stillbirth in low-income and middle-income countries](https://doi.org/10.1016/S2214-109X(19)30458-9)." The Lancet Global Health 8 (1): e16-e17.

-   Erku, D., P. Scuffham, K. Gething, R. Norman, A. B. Mekonnen, G. B. Gebretekle, Y. Assefa, and G. Tessema. 2021. "[Stated Preference Research in Reproductive and Maternal Healthcare Services in Sub-Saharan Africa: A Systematic Review.](10.1007/s40271-021-00553-9)" The Patient: Patient Centered Outcomes Research 15: 287-306.

-   Tessema, G. A., T. M. Berheto, G. Pereira, A. Misganaw, and Y. Kinfu. 2023. "[National and subnational burden of under-5, infant, and neonatal mortality in Ethiopia, 1990–2019: Findings from the Global Burden of Disease Study 2019](10.1371/journal.pgph.0001471)." PLOS Global Public Health 3 (6)

-   Haile, T. G., G. Pereira, R. Norman, and G. A. Tessema. 2024. "[Economic burden of adverse perinatal outcomes from births to age 5 years in high-income settings: A protocol for a systematic review.](10.1136/bmjopen-2023-079077)" BMJ Open 14 (1)
